from __future__ import annotations

# Context-sensitive examples keyed by Slovak target + its Ukrainian meaning.
# Generated from the regression corpus; edit the corpus first, then rematerialize.
CONTEXTUAL_EXAMPLES = {('ako', 'як / ніж'): ('Môj brat je vyšší ako ja.', 'Мій брат вищий за мене.'),
 ('bol som na', 'я був на'): ('Bol som na stanici.', 'Я був на вокзалі.'),
 ('bol som v', 'я був у / в'): ('Bol som v centre.', 'Я був у центрі.'),
 ('chcem', 'я хочу'): ('Chcem ísť domov.', 'Я хочу піти додому.'),
 ('chystať sa', 'збиратися щось зробити'): ('Chystám sa cestovať.', 'Я збираюся подорожувати.'),
 ('chýbať', 'бракувати'): ('Môže nám chýbať mlieko.', 'Нам може бракувати молока.'),
 ('cítiť sa', 'почуватися'): ('Chcem sa cítiť lepšie.', 'Я хочу почуватися краще.'),
 ('dobre', 'добре'): ('Cítim sa dobre.', 'Я почуваюся добре.'),
 ('dohodnúť', 'домовитися'): ('Musíme dohodnúť termín.', 'Ми маємо домовитися про час.'),
 ('dohodnúť sa', 'домовитися'): ('Chceme sa dohodnúť na čase.', 'Ми хочемо домовитися про час.'),
 ('dokončiť', 'завершити'): ('Chcem dokončiť projekt.', 'Я хочу завершити проєкт.'),
 ('dostať sa', 'дістатися'): ('Ako sa môžem dostať na stanicu?', 'Як я можу дістатися до вокзалу?'),
 ('dosť', 'достатньо'): ('Mám dosť vody.', 'У мене достатньо води.'),
 ('dvere', 'двері'): ('To sú dvere.', 'Це двері.'),
 ('hrať', 'грати'): ('Chcem hrať futbal.', 'Я хочу грати у футбол.'),
 ('hádať sa', 'сваритися'): ('Nechcem sa hádať kvôli maličkostiam.', 'Я не хочу сваритися через дрібниці.'),
 ('hľadám', 'я шукаю'): ('Hľadám oddelenie s elektronikou.', 'Я шукаю відділ електроніки.'),
 ('inokedy', 'іншим разом'): ('Môžeme sa stretnúť inokedy.', 'Ми можемо зустрітися іншим разом.'),
 ('jasné', 'звісно / добре'): ('Jasné, pomôžem ti.', 'Звісно, я тобі допоможу.'),
 ('kde', 'де'): ('Kde sa stretneme?', 'Де ми зустрінемося?'),
 ('kedy', 'коли'): ('Kedy sa stretneme?', 'Коли ми зустрінемося?'),
 ('končiť', 'закінчувати'): ('Kurz môže končiť o piatej.', 'Курс може закінчуватися о п’ятій.'),
 ('kvapky', 'краплі'): ('To sú kvapky.', 'Це краплі.'),
 ('kúpiť', 'купити'): ('Chcem kúpiť chlieb.', 'Я хочу купити хліб.'),
 ('lebo', 'бо'): ('Zostanem doma, lebo som chorý.', 'Я залишуся вдома, бо я хворий.'),
 ('medzi', 'між'): ('Kaviareň je medzi bankou a poštou.', 'Кав’ярня між банком і поштою.'),
 ('medzitým', 'тим часом'): ('Medzitým som pripravil večeru.', 'Тим часом я приготував вечерю.'),
 ('menej', 'менше'): ('Mám menej práce.', 'У мене менше роботи.'),
 ('meškať', 'запізнюватися'): ('Autobus môže meškať desať minút.', 'Автобус може запізнюватися на десять хвилин.'),
 ('musím', 'я мушу'): ('Musím pracovať.', 'Я мушу працювати.'),
 ('mám rád', 'я люблю'): ('Mám rád polievku.', 'Я люблю суп.'),
 ('máte', 'у вас є'): ('Máte túto veľkosť?', 'У вас є цей розмір?'),
 ('môžem sa spoľahnúť', 'я можу покластися'): ('Môžem sa na neho spoľahnúť.', 'Я можу на нього покластися.'),
 ('môžeme', 'ми можемо'): ('Môžeme sa stretnúť zajtra.', 'Ми можемо зустрітися завтра.'),
 ('nabudúce', 'наступного разу'): ('Prídem nabudúce.', 'Я прийду наступного разу.'),
 ('namiesto', 'замість'): ('Pôjdem vlakom namiesto autobusu.', 'Я поїду потягом замість автобуса.'),
 ('napísať', 'написати'): ('Chcem napísať správu.', 'Я хочу написати повідомлення.'),
 ('napíšem', 'я напишу'): ('Napíšem ti správu.', 'Я напишу тобі повідомлення.'),
 ('nastúpiť', 'сісти в транспорт'): ('Musíte nastúpiť do autobusu.', 'Вам потрібно сісти в автобус.'),
 ('naučiť sa', 'вивчити / навчитися'): ('Chcem sa naučiť po slovensky.', 'Я хочу навчитися говорити словацькою.'),
 ('navrhnúť', 'запропонувати'): ('Chcem navrhnúť riešenie.', 'Я хочу запропонувати рішення.'),
 ('navrhujem', 'я пропоную'): ('Navrhujem stretnutie o šiestej.', 'Я пропоную зустрітися о шостій.'),
 ('navštíviť', 'відвідати'): ('Chcem navštíviť rodinu.', 'Я хочу відвідати родину.'),
 ('nefunguje', 'не працює'): ('Výťah nefunguje.', 'Ліфт не працює.'),
 ('nejde', 'не працює / не йде'): ('Výťah nejde.', 'Ліфт не працює.'),
 ('nemám rád', 'я не люблю'): ('Nemám rád mäso.', 'Я не люблю м’ясо.'),
 ('nemôžeme', 'ми не можемо'): ('Dnes sa nemôžeme stretnúť.', 'Сьогодні ми не можемо зустрітися.'),
 ('nerád', 'неохоче / не люблю'): ('Nerád vstávam skoro.', 'Я не люблю рано вставати.'),
 ('nestíhať', 'не встигати'): ('Môžem nestíhať autobus, ak odídem neskoro.',
                               'Я можу не встигнути на автобус, якщо вийду пізно.'),
 ('nesvieti', 'не світить'): ('Lampa nesvieti.', 'Лампа не світить.'),
 ('nesúhlasiť', 'не погоджуватися'): ('Môžem nesúhlasiť a vysvetliť prečo.', 'Я можу не погодитися й пояснити чому.'),
 ('nájsť', 'знайти'): ('Chcem nájsť svoje kľúče.', 'Я хочу знайти свої ключі.'),
 ('odbočiť', 'повернути'): ('Tu musíte odbočiť vľavo.', 'Тут вам потрібно повернути ліворуч.'),
 ('odišiel som z', 'я пішов / виїхав з'): ('Odišiel som z práce.', 'Я пішов з роботи.'),
 ('odložiť', 'відкласти'): ('Musím odložiť stretnutie.', 'Я мушу відкласти зустріч.'),
 ('odpísať', 'відповісти'): ('Musím odpísať na správu.', 'Я мушу відповісти на повідомлення.'),
 ('odtiaľ', 'звідти'): ('Odtiaľ choďte rovno.', 'Звідти йдіть прямо.'),
 ('opakovať', 'повторювати'): ('Musím opakovať učivo.', 'Мені треба повторювати навчальний матеріал.'),
 ('opraviť', 'полагодити'): ('Chcem opraviť lampu.', 'Я хочу полагодити лампу.'),
 ('oproti', 'навпроти'): ('Lekáreň je oproti banke.', 'Аптека навпроти банку.'),
 ('ozvať sa', 'дати знати'): ('Ozvem sa večer.', 'Я дам знати ввечері.'),
 ('ozvať sa', 'дати знати / відгукнутися'): ('Ozvem sa večer.', 'Я дам знати ввечері.'),
 ('plánovať', 'планувати'): ('Chcem plánovať týždeň vopred.', 'Я хочу планувати тиждень наперед.'),
 ('pokračovať', 'продовжувати'): ('Môžete pokračovať rovno.', 'Можете продовжувати прямо.'),
 ('pomôcť', 'допомогти'): ('Chcem pomôcť kolegovi.', 'Я хочу допомогти колезі.'),
 ('pomôcť si', 'допомогти одне одному'): ('Môžeme si navzájom pomôcť.', 'Ми можемо допомогти одне одному.'),
 ('ponáhľať sa', 'поспішати'): ('Ráno sa nemusím ponáhľať.', 'Вранці мені не потрібно поспішати.'),
 ('poslať', 'надіслати'): ('Chcem poslať balík.', 'Я хочу надіслати посилку.'),
 ('potom môžeme', 'потім ми можемо'): ('Potom môžeme ísť na kávu.', 'Потім ми можемо піти на каву.'),
 ('potrebovať', 'потребувати'): ('Môžeme potrebovať viac zeleniny.', 'Нам може знадобитися більше овочів.'),
 ('potrebujem', 'мені потрібно'): ('Potrebujem pomoc.', 'Мені потрібна допомога.'),
 ('potvrdiť', 'підтвердити'): ('Chcem potvrdiť termín.', 'Я хочу підтвердити час.'),
 ('pozerať', 'дивитися'): ('Chcem pozerať film.', 'Я хочу дивитися фільм.'),
 ('poznať', 'знати / бути знайомим'): ('Chcem lepšie poznať svojho suseda.', 'Я хочу краще знати свого сусіда.'),
 ('pozvať', 'запросити'): ('Chcem pozvať kamarátov.', 'Я хочу запросити друзів.'),
 ('počúvať', 'слухати'): ('Chcem počúvať hudbu.', 'Я хочу слухати музику.'),
 ('poškodiť', 'пошкодити'): ('Nechcem poškodiť telefón.', 'Я не хочу пошкодити телефон.'),
 ('prenajímať', 'орендувати'): ('Chcem prenajímať byt.', 'Я хочу здавати квартиру в оренду.'),
 ('prepáč', 'вибач'): ('Prepáč, meškám.', 'Вибач, я запізнююся.'),
 ('prestať', 'перестати'): ('Chcem prestať chodiť spať neskoro.', 'Я хочу перестати пізно лягати спати.'),
 ('prestúpiť', 'пересісти'): ('Musíte prestúpiť na električku.', 'Вам потрібно пересісти на трамвай.'),
 ('preto', 'тому'): ('Som chorý, preto zostanem doma.', 'Я хворий, тому залишуся вдома.'),
 ('pretože', 'тому що'): ('Páči sa mi to, pretože je to zaujímavé.', 'Мені це подобається, тому що це цікаво.'),
 ('pridať sa', 'приєднатися'): ('Chcem sa pridať k vám.', 'Я хочу приєднатися до вас.'),
 ('pripraviť sa', 'підготуватися'): ('Musím sa pripraviť na skúšku.', 'Я мушу підготуватися до іспиту.'),
 ('prišiel som do', 'я прийшов до / в'): ('Prišiel som do hotela.', 'Я прийшов до готелю.'),
 ('prídem', 'я прийду'): ('Prídem o šiestej.', 'Я прийду о шостій.'),
 ('prísť', 'прийти'): ('Technik môže prísť zajtra.', 'Технік може прийти завтра.'),
 ('prísť pozrieť', 'прийти подивитися'): ('Technik môže prísť pozrieť kotol.', 'Технік може прийти подивитися котел.'),
 ('páčiť sa', 'подобатися'): ('Páči sa mi tento film.', 'Мені подобається цей фільм.'),
 ('pôjdeme', 'ми підемо / поїдемо'): ('Pôjdeme autobusom.', 'Ми поїдемо автобусом.'),
 ('radšej', 'радше / краще'): ('Radšej pôjdem vlakom.', 'Я радше поїду потягом.'),
 ('rezervovať', 'бронювати'): ('Chcem rezervovať izbu.', 'Я хочу забронювати номер.'),
 ('rovnako', 'однаково'): ('Máme to rovnako.', 'У нас це однаково.'),
 ('rozdeliť si', 'розподілити між собою'): ('Musíme si rozdeliť úlohy.', 'Ми маємо розподілити завдання між собою.'),
 ('rozhodnúť sa', 'вирішити'): ('Musím sa rozhodnúť dnes.', 'Я мушу вирішити сьогодні.'),
 ('rozhodnúť sa', 'вирішити / прийняти рішення'): ('Musím sa rozhodnúť dnes.', 'Я мушу прийняти рішення сьогодні.'),
 ('rozumieť si', 'розуміти одне одного'): ('Dobre si rozumieme.', 'Ми добре розуміємо одне одного.'),
 ('rušiť', 'заважати'): ('Nechcem rušiť susedov.', 'Я не хочу заважати сусідам.'),
 ('rád', 'охоче / люблю'): ('Rád čítam.', 'Я люблю читати.'),
 ('samozrejme', 'звичайно'): ('Samozrejme, pomôžem.', 'Звичайно, я допоможу.'),
 ('skôr', 'раніше'): ('Chcem chodiť spať skôr.', 'Я хочу раніше лягати спати.'),
 ('skôr', 'скоріше'): ('Skôr by som išiel vlakom.', 'Я радше поїхав би потягом.'),
 ('skúsiť', 'спробувати'): ('Chcem skúsiť iné riešenie.', 'Я хочу спробувати інше рішення.'),
 ('smerom', 'у напрямку'): ('Choďte smerom k centru.', 'Ідіть у напрямку центру.'),
 ('spolu', 'разом'): ('Pôjdeme spolu.', 'Ми підемо разом.'),
 ('spolupracovať', 'співпрацювати'): ('Chcem spolupracovať s tímom.', 'Я хочу співпрацювати з командою.'),
 ('stihnúť', 'встигнути'): ('Musím to stihnúť dnes.', 'Я мушу встигнути це сьогодні.'),
 ('stratiť', 'загубити'): ('Nechcem stratiť kľúče.', 'Я не хочу загубити ключі.'),
 ('stretneme sa', 'ми зустрінемося'): ('Stretneme sa o šiestej.', 'Ми зустрінемося о шостій.'),
 ('stretávať sa', 'зустрічатися'): ('Často sa stretávame cez víkend.', 'Ми часто зустрічаємося на вихідних.'),
 ('stáť', 'коштувати'): ('Koľko to môže stáť?', 'Скільки це може коштувати?'),
 ('stíhať', 'встигати'): ('Chcem stíhať všetky povinnosti načas.', 'Я хочу встигати виконувати всі справи вчасно.'),
 ('súhlasiť', 'погоджуватися'): ('Môžem s tým súhlasiť.', 'Я можу з цим погодитися.'),
 ('súhlasiť', 'погодитися'): ('Môžem s tým súhlasiť.', 'Я можу з цим погодитися.'),
 ('sýty', 'ситий'): ('Som sýty.', 'Я ситий.'),
 ('sťažovať sa', 'скаржитися'): ('Nechcem sa sťažovať na hluk.', 'Я не хочу скаржитися на шум.'),
 ('tadiaľ', 'цією дорогою'): ('Choďte tadiaľ.', 'Ідіть цією дорогою.'),
 ('tečie', 'тече'): ('Z kohútika tečie voda.', 'З крана тече вода.'),
 ('tešiť sa', 'радіти / чекати з нетерпінням'): ('Teším sa na víkend.', 'Я з нетерпінням чекаю на вихідні.'),
 ('trvať', 'тривати'): ('Cesta môže trvať desať minút.', 'Дорога може тривати десять хвилин.'),
 ('určite', 'точно / безумовно'): ('Určite prídem.', 'Я точно прийду.'),
 ('užívať', 'приймати ліки'): ('Ako mám užívať tento liek?', 'Як мені приймати ці ліки?'),
 ('vedľa', 'поруч'): ('Banka je vedľa pošty.', 'Банк поруч із поштою.'),
 ('viac', 'більше'): ('Chcem viac času.', 'Я хочу більше часу.'),
 ('vložiť', 'внести'): ('Chcem vložiť peniaze na účet.', 'Я хочу внести гроші на рахунок.'),
 ('vrátiť', 'повернути'): ('Chcem vrátiť tento tovar.', 'Я хочу повернути цей товар.'),
 ('vybavené', 'готово / вирішено'): ('Je to vybavené.', 'Це вже владнано.'),
 ('vybaviť', 'залагодити'): ('Chcem vybaviť túto vec dnes.', 'Я хочу владнати цю справу сьогодні.'),
 ('vybaviť', 'залагодити / зробити справу'): ('Musím vybaviť jednu vec.', 'Мені треба владнати одну справу.'),
 ('vybavovať', 'залагоджувати'): ('Dopoludnia budem vybavovať veci.', 'До обіду я владнуватиму справи.'),
 ('vybavovať', 'залагоджувати справи'): ('Dopoludnia musím vybavovať veci.', 'До обіду мені треба владнувати справи.'),
 ('vybrať', 'зняти'): ('Chcem vybrať hotovosť.', 'Я хочу зняти готівку.'),
 ('vybrať si', 'обрати'): ('Musím si vybrať jednu možnosť.', 'Я мушу обрати один варіант.'),
 ('vyhovovať', 'підходити'): ('Tento termín mi môže vyhovovať.', 'Цей час може мені підійти.'),
 ('vymeniť', 'обміняти'): ('Chcem vymeniť túto košeľu.', 'Я хочу обміняти цю сорочку.'),
 ('vyriešiť', 'вирішити'): ('Musíme vyriešiť problém.', 'Ми маємо вирішити проблему.'),
 ('vyskúšať si', 'приміряти'): ('Chcem si vyskúšať tieto topánky.', 'Я хочу приміряти ці черевики.'),
 ('vystúpiť', 'вийти'): ('Vystúpte na tretej zastávke.', 'Вийдіть на третій зупинці.'),
 ('vystúpiť', 'вийти з транспорту'): ('Musíte vystúpiť na tretej zastávke.', 'Вам потрібно вийти на третій зупинці.'),
 ('vysvetliť', 'пояснити'): ('Môžete mi to vysvetliť?', 'Можете мені це пояснити?'),
 ('zablúdiť', 'заблукати'): ('Nechcem zablúdiť v centre.', 'Я не хочу заблукати в центрі.'),
 ('zabudnúť', 'забути'): ('Nechcem zabudnúť kľúče.', 'Я не хочу забути ключі.'),
 ('zajtra', 'завтра'): ('Prídem zajtra.', 'Я прийду завтра.'),
 ('zavolať', 'зателефонувати'): ('Musím zavolať opravára.', 'Я мушу зателефонувати майстру.'),
 ('zavolám', 'я зателефоную'): ('Zavolám ti večer.', 'Я зателефоную тобі ввечері.'),
 ('začať', 'почати'): ('Chcem začať cvičiť.', 'Я хочу почати тренуватися.'),
 ('začínať', 'починати'): ('Práca môže začínať o ôsmej.', 'Робота може починатися о восьмій.'),
 ('zle', 'погано'): ('Cítim sa zle.', 'Я почуваюся погано.'),
 ('zlepšiť sa', 'покращитися'): ('Môj stav sa môže zlepšiť.', 'Мій стан може покращитися.'),
 ('zmeniť', 'змінити'): ('Chcem zmeniť svoj návyk.', 'Я хочу змінити свою звичку.'),
 ('zvládnuť', 'впоратися'): ('Chcem zvládnuť túto úlohu.', 'Я хочу впоратися з цим завданням.'),
 ('čakať', 'чекати'): ('Musím čakať v rade.', 'Я мушу чекати в черзі.'),
 ('žiaľ', 'на жаль'): ('Žiaľ, nemôžem prísť.', 'На жаль, я не можу прийти.')}
