from __future__ import annotations

# Curated examples for targets where generic morphology is not enough to produce
# a natural, complete A2 sentence. Keys are normalized lowercase Slovak targets.
EXAMPLES: dict[str, tuple[str, str]] = {
    'baví ma': ('Baví ma učiť sa po slovensky.', 'Мені подобається вчити словацьку.'),
    'nebaví ma': ('Nebaví ma dlho čakať.', 'Мені не подобається довго чекати.'),
    'zaujíma ma': ('Zaujíma ma slovenská kultúra.', 'Мене цікавить словацька культура.'),
    'nezaujíma ma': ('Nezaujíma ma futbal.', 'Мене не цікавить футбол.'),
    'starí rodičia': ('Moji starí rodičia bývajú na dedine.', 'Мої дідусь і бабуся живуть у селі.'),
    'pomáha mi': ('Pomáha mi s úlohou.', 'Він або вона допомагає мені із завданням.'),
    'bežný deň': ('Dnes je bežný deň.', 'Сьогодні звичайний день.'),
    'počas dňa': ('Počas dňa veľa pracujem.', 'Протягом дня я багато працюю.'),
    'každý deň': ('Každý deň chodím pešo.', 'Щодня я ходжу пішки.'),
    'každý týždeň': ('Každý týždeň plánujem ďalšie dni.', 'Щотижня я планую наступні дні.'),
    'dvakrát týždenne': ('Cvičím dvakrát týždenne.', 'Я тренуюся двічі на тиждень.'),
    'skoro nikdy': ('Skoro nikdy nepozerám televíziu.', 'Я майже ніколи не дивлюся телевізор.'),
    'raz za čas': ('Raz za čas idem do kina.', 'Час від часу я ходжу в кіно.'),
    'mať čas': ('Chcem mať čas aj na oddych.', 'Я хочу мати час і на відпочинок.'),
    'nemať čas': ('Môžem večer nemať čas.', 'Увечері в мене може не бути часу.'),
    'dnes už': ('Dnes už nemám čas.', 'Сьогодні в мене вже немає часу.'),
    'cez víkend': ('Cez víkend oddychujem.', 'На вихідних я відпочиваю.'),
    'zostať doma': ('Chcem zostať doma.', 'Я хочу залишитися вдома.'),
    'ísť von': ('Večer chcem ísť von.', 'Увечері я хочу кудись піти.'),
    'celý deň': ('Som doma celý deň.', 'Я вдома цілий день.'),
    'pracovný deň': ('Dnes je pracovný deň.', 'Сьогодні робочий день.'),
    'voľný deň': ('V nedeľu mám voľný deň.', 'У неділю в мене вихідний.'),
    'minulú sobotu': ('Minulú sobotu sme boli v meste.', 'Минулої суботи ми були в місті.'),
    'minulú nedeľu': ('Minulú nedeľu sme zostali doma.', 'Минулої неділі ми залишилися вдома.'),
    'stalo sa': ('Stalo sa to včera.', 'Це сталося вчора.'),
    'bolo to': ('Bolo to veľmi zaujímavé.', 'Це було дуже цікаво.'),
    'bolo tam': ('Bolo tam veľa ľudí.', 'Там було багато людей.'),
    'veľmi sa mi páčilo': ('Veľmi sa mi to páčilo.', 'Мені це дуже сподобалося.'),
    'nepáčilo sa mi': ('Vôbec sa mi to nepáčilo.', 'Мені це зовсім не сподобалося.'),
    'budúci týždeň': ('Budúci týždeň budem pracovať z domu.', 'Наступного тижня я працюватиму з дому.'),
    'vyhovuje mi': ('Vyhovuje mi tento termín.', 'Мені підходить цей час.'),
    'nevyhovuje mi': ('Nevyhovuje mi tento termín.', 'Мені не підходить цей час.'),
    'zmeniť plán': ('Musím zmeniť plán.', 'Я мушу змінити план.'),
    'bývať spolu': ('Chceme bývať spolu.', 'Ми хочемо жити разом.'),
    'domáce práce': ('Večer robím domáce práce.', 'Увечері я займаюся домашніми справами.'),
    'ísť rovno': ('Musíte ísť rovno.', 'Вам потрібно йти прямо.'),
    'cez ulicu': ('Prejdite cez ulicu.', 'Перейдіть через вулицю.'),
    'na konci': ('Pošta je na konci ulice.', 'Пошта в кінці вулиці.'),
    'pri križovatke': ('Zastávka je pri križovatke.', 'Зупинка біля перехрестя.'),
    'ďalšia zastávka': ('Ďalšia zastávka je centrum.', 'Наступна зупинка — центр.'),
    'posledná zastávka': ('Toto je posledná zastávka.', 'Це кінцева зупинка.'),
    'ako dlho': ('Ako dlho to trvá?', 'Як довго це триває?'),
    'asi desať minút': ('Trvá to asi desať minút.', 'Це триває приблизно десять хвилин.'),
    'chutí mi': ('Chutí mi táto polievka.', 'Мені смакує цей суп.'),
    'nechutí mi': ('Nechutí mi táto polievka.', 'Мені не смакує цей суп.'),
    'pol kila': ('Potrebujem pol kila jabĺk.', 'Мені потрібно пів кілограма яблук.'),
    'pol litra': ('Potrebujem pol litra mlieka.', 'Мені потрібно пів літра молока.'),
    'dať do': ('Treba to dať do hrnca.', 'Це потрібно покласти в каструлю.'),
    'mať doma': ('Chcem to mať doma.', 'Я хочу мати це вдома.'),
    'pripraviť večeru': ('Chcem pripraviť večeru.', 'Я хочу приготувати вечерю.'),
    'sedí mi': ('Sedí mi táto veľkosť.', 'Мені підходить цей розмір.'),
    'nesedí mi': ('Nesedí mi táto veľkosť.', 'Мені не підходить цей розмір.'),
    'peniaze späť': ('Chcem peniaze späť.', 'Я хочу гроші назад.'),
    'pracovať na': ('Budem pracovať na projekte.', 'Я працюватиму над проєктом.'),
    'začínať o': ('Práca môže začínať o ôsmej.', 'Робота може починатися о восьмій.'),
    'končiť o': ('Práca môže končiť o piatej.', 'Робота може закінчуватися о п’ятій.'),
    'obedná prestávka': ('Obedná prestávka trvá pol hodiny.', 'Обідня перерва триває пів години.'),
    'veľa práce': ('Dnes mám veľa práce.', 'Сьогодні в мене багато роботи.'),
    'málo času': ('Mám málo času.', 'У мене мало часу.'),
    'potrebovať pomoc': ('Každý môže potrebovať pomoc.', 'Кожному може знадобитися допомога.'),
    'voľný čas': ('Vo voľnom čase čítam.', 'У вільний час я читаю.'),
    'mrzí ma to': ('Mrzí ma to, dnes nemôžem prísť.', 'Мені шкода, сьогодні я не можу прийти.'),
    'ráno sa stretneme': ('Ráno sa stretneme pred stanicou.', 'Вранці ми зустрінемося перед вокзалом.'),
    'večer sa vrátime': ('Večer sa vrátime domov.', 'Увечері ми повернемося додому.'),
    'môžete zopakovať': ('Môžete zopakovať poslednú vetu?', 'Можете повторити останнє речення?'),
    'čo to znamená': ('Čo to znamená po slovensky?', 'Що це означає словацькою?'),
    'ešte raz': ('Povedzte to ešte raz, prosím.', 'Скажіть це ще раз, будь ласка.'),
    'zdvihnúť telefón': ('Musím zdvihnúť telefón.', 'Я мушу підняти слухавку.'),
    'nechať odkaz': ('Chcem nechať odkaz.', 'Я хочу залишити повідомлення.'),
    'o chvíľu': ('Zavolám vám o chvíľu.', 'Я зателефоную вам незабаром.'),
    'dostať správu': ('Chcem dostať správu.', 'Я хочу отримати повідомлення.'),
    'na pár dní': ('Ideme tam na pár dní.', 'Ми їдемо туди на кілька днів.'),
    'voľná izba': ('Je ešte voľná izba?', 'Чи є ще вільний номер?'),
    'zmeniť rezerváciu': ('Potrebujem zmeniť rezerváciu.', 'Мені потрібно змінити бронювання.'),
    'bolí ma': ('Bolí ma hlava.', 'У мене болить голова.'),
    'bez receptu': ('Je tento liek bez receptu?', 'Ці ліки без рецепта?'),
    'dvakrát denne': ('Beriem liek dvakrát denne.', 'Я приймаю ліки двічі на день.'),
    'podľa mňa áno': ('Podľa mňa áno, je to dobrý nápad.', 'На мою думку, так, це добра ідея.'),
    'podľa mňa nie': ('Podľa mňa nie, je to príliš drahé.', 'На мою думку, ні, це надто дорого.'),
    'kvôli tomu': ('Kvôli tomu meškám.', 'Через це я запізнююся.'),
    'dobrý nápad': ('To je dobrý nápad.', 'Це добра ідея.'),
    'zlý nápad': ('To je zlý nápad.', 'Це погана ідея.'),
    'posledné dni': ('Posledné dni veľa pracujem.', 'Останніми днями я багато працюю.'),
    'zmena plánu': ('Nastala zmena plánu.', 'Сталася зміна плану.'),
    'niekedy': ('Niekedy chodím do kina.', 'Іноді я ходжу в кіно.'),
    'málokedy': ('Málokedy pozerám televíziu.', 'Я рідко дивлюся телевізор.'),
    'vôbec': ('Vôbec tomu nerozumiem.', 'Я зовсім цього не розумію.'),
    'ráno': ('Ráno pijem kávu.', 'Вранці я п’ю каву.'),
    'dopoludnia': ('Dopoludnia pracujem.', 'До обіду я працюю.'),
    'popoludní': ('Popoludní mám voľno.', 'Після обіду я вільний або вільна.'),
    'večer': ('Večer zostávam doma.', 'Увечері я залишаюся вдома.'),
    'najprv': ('Najprv si dám raňajky.', 'Спочатку я поснідаю.'),
    'potom': ('Potom idem do práce.', 'Потім я йду на роботу.'),
    'neskôr': ('Zavolám ti neskôr.', 'Я зателефоную тобі пізніше.'),
    'nakoniec': ('Nakoniec sme zostali doma.', 'Зрештою ми залишилися вдома.'),
    'zvyčajne': ('Zvyčajne chodím pešo.', 'Зазвичай я ходжу пішки.'),
    'pravidelne': ('Pravidelne cvičím.', 'Я регулярно тренуюся.'),
    'občas': ('Občas varím doma.', 'Час від часу я готую вдома.'),
    'zrazu': ('Zrazu začalo pršať.', 'Раптом почався дощ.'),
    'našťastie': ('Našťastie sa nič nestalo.', 'На щастя, нічого не сталося.'),
    'bohužiaľ': ('Bohužiaľ dnes nemôžem prísť.', 'На жаль, сьогодні я не можу прийти.'),
    'možno': ('Možno prídem neskôr.', 'Можливо, я прийду пізніше.'),
    'asi': ('Asi prídem o šiestej.', 'Мабуть, я прийду о шостій.'),
    'pravdepodobne': ('Pravdepodobne zostanem doma.', 'Ймовірно, я залишуся вдома.'),
    'vľavo': ('Pošta je vľavo.', 'Пошта ліворуч.'),
    'hore': ('Spálňa je hore.', 'Спальня нагорі.'),
    'dole': ('Kuchyňa je dole.', 'Кухня внизу.'),
    'vpredu': ('Vodič sedí vpredu.', 'Водій сидить спереду.'),
    'vzadu': ('Sedíme vzadu.', 'Ми сидимо позаду.'),
    'blízko': ('Lekáreň je blízko.', 'Аптека близько.'),
    'ďaleko': ('Stanica je ďaleko.', 'Вокзал далеко.'),
    'približne': ('Cesta trvá približne hodinu.', 'Дорога триває приблизно годину.'),
    'úspešne': ('Všetko sa úspešne skončilo.', 'Усе успішно завершилося.'),
    'pomalšie': ('Hovorte, prosím, pomalšie.', 'Говоріть, будь ласка, повільніше.'),
    'inak': ('Skúste to povedať inak.', 'Спробуйте сказати це інакше.'),
    'hneď': ('Prídem hneď.', 'Я прийду одразу.'),
    'lepšie': ('Dnes sa cítim lepšie.', 'Сьогодні я почуваюся краще.'),
    'horšie': ('Dnes sa cítim horšie.', 'Сьогодні я почуваюся гірше.'),
    'hlavne': ('Chodím tam hlavne cez víkend.', 'Я ходжу туди переважно на вихідних.'),
    'najmä': ('Kupujem najmä zeleninu.', 'Я купую переважно овочі.'),
    'momentálne': ('Momentálne pracujem z domu.', 'Зараз я працюю з дому.'),
    'kedysi': ('Kedysi tu bola pošta.', 'Колись тут була пошта.'),
    'teraz': ('Teraz nemám čas.', 'Тепер у мене немає часу.'),
    'bol som': ('Bol som doma.', 'Я був удома.'),
    'mal som': ('Mal som veľa práce.', 'У мене було багато роботи.'),
    'robil som': ('Robil som doma.', 'Я працював удома.'),
    'prišiel som': ('Prišiel som neskoro.', 'Я прийшов пізно.'),
    'išiel som': ('Išiel som domov.', 'Я пішов додому.'),
    'boli sme': ('Boli sme doma.', 'Ми були вдома.'),
    'išli sme': ('Išli sme do mesta.', 'Ми пішли до міста.'),
    'zostali sme': ('Zostali sme doma.', 'Ми залишилися вдома.'),
    'navštívili sme': ('Navštívili sme rodinu.', 'Ми відвідали родину.'),
    'vybavil som': ('Vybavil som všetko.', 'Я все владнав.'),
}
