import unittest
from tools.a2_build.generator import example_for

CASES = [
    ('rád','охоче / люблю',('Rád čítam.','Я люблю читати.')),
    ('nerád','неохоче / не люблю',('Nerád vstávam skoro.','Я не люблю рано вставати.')),
    ('poznať','знати / бути знайомим',('Chcem lepšie poznať svojho suseda.','Я хочу краще знати свого сусіда.')),
    ('stretávať sa','зустрічатися',('Často sa stretávame cez víkend.','Ми часто зустрічаємося на вихідних.')),
    ('rozumieť si','розуміти одне одного',('Dobre si rozumieme.','Ми добре розуміємо одне одного.')),
    ('hádať sa','сваритися',('Nechcem sa hádať kvôli maličkostiam.','Я не хочу сваритися через дрібниці.')),
    ('súhlasiť','погоджуватися',('Môžem s tým súhlasiť.','Я можу з цим погодитися.')),
    ('nesúhlasiť','не погоджуватися',('Môžem nesúhlasiť a vysvetliť prečo.','Я можу не погодитися й пояснити чому.')),
    ('rovnako','однаково',('Máme to rovnako.','У нас це однаково.')),
    ('viac','більше',('Chcem viac času.','Я хочу більше часу.')),
    ('menej','менше',('Mám menej práce.','У мене менше роботи.')),
    ('ako','як / ніж',('Môj brat je vyšší ako ja.','Мій брат вищий за мене.')),
    ('môžem sa spoľahnúť','я можу покластися',('Môžem sa na neho spoľahnúť.','Я можу на нього покластися.')),
    ('stíhať','встигати',('Chcem stíhať všetky povinnosti načas.','Я хочу встигати виконувати всі справи вчасно.')),
    ('nestíhať','не встигати',('Môžem nestíhať autobus, ak odídem neskoro.','Я можу не встигнути на автобус, якщо вийду пізно.')),
    ('ponáhľať sa','поспішати',('Ráno sa nemusím ponáhľať.','Вранці мені не потрібно поспішати.')),
    ('odložiť','відкласти',('Musím odložiť stretnutie.','Я мушу відкласти зустріч.')),
    ('vybaviť','залагодити / зробити справу',('Musím vybaviť jednu vec.','Мені треба владнати одну справу.')),
    ('navštíviť','відвідати',('Chcem navštíviť rodinu.','Я хочу відвідати родину.')),
    ('zmeniť','змінити',('Chcem zmeniť svoj návyk.','Я хочу змінити свою звичку.')),
    ('začať','почати',('Chcem začať cvičiť.','Я хочу почати тренуватися.')),
    ('prestať','перестати',('Chcem prestať chodiť spať neskoro.','Я хочу перестати пізно лягати спати.')),
    ('skôr','раніше',('Chcem chodiť spať skôr.','Я хочу раніше лягати спати.')),
    ('plánovať','планувати',('Chcem plánovať týždeň vopred.','Я хочу планувати тиждень наперед.')),
    ('vybavovať','залагоджувати справи',('Dopoludnia musím vybavovať veci.','До обіду мені треба владнувати справи.')),
    ('stihnúť','встигнути',('Musím to stihnúť dnes.','Я мушу встигнути це сьогодні.')),
    ('začínať','починати',('Práca môže začínať o ôsmej.','Робота може починатися о восьмій.')),
    ('končiť','закінчувати',('Kurz môže končiť o piatej.','Курс може закінчуватися о п’ятій.')),
    ('zabudnúť','забути',('Nechcem zabudnúť kľúče.','Я не хочу забути ключі.')),
    ('nájsť','знайти',('Chcem nájsť svoje kľúče.','Я хочу знайти свої ключі.')),
    ('bol som v','я був у / в',('Bol som v centre.','Я був у центрі.')),
    ('bol som na','я був на',('Bol som na stanici.','Я був на вокзалі.')),
    ('prišiel som do','я прийшов до / в',('Prišiel som do hotela.','Я прийшов до готелю.')),
    ('odišiel som z','я пішов / виїхав з',('Odišiel som z práce.','Я пішов з роботи.')),
    ('medzitým','тим часом',('Medzitým som pripravil večeru.','Тим часом я приготував вечерю.')),
    ('zajtra','завтра',('Prídem zajtra.','Я прийду завтра.')),
    ('prídem','я прийду',('Prídem o šiestej.','Я прийду о шостій.')),
    ('zavolám','я зателефоную',('Zavolám ti večer.','Я зателефоную тобі ввечері.')),
    ('napíšem','я напишу',('Napíšem ti správu.','Я напишу тобі повідомлення.')),
    ('rozhodnúť sa','вирішити',('Musím sa rozhodnúť dnes.','Я мушу вирішити сьогодні.')),
    ('chystať sa','збиратися щось зробити',('Chystám sa cestovať.','Я збираюся подорожувати.')),
    ('chcem','я хочу',('Chcem ísť domov.','Я хочу піти додому.')),
    ('potrebujem','мені потрібно',('Potrebujem pomoc.','Мені потрібна допомога.')),
    ('musím','я мушу',('Musím pracovať.','Я мушу працювати.')),
    ('dohodnúť sa','домовитися',('Chceme sa dohodnúť na čase.','Ми хочемо домовитися про час.')),
    ('kedy','коли',('Kedy sa stretneme?','Коли ми зустрінемося?')),
    ('kde','де',('Kde sa stretneme?','Де ми зустрінемося?')),
    ('môžeme','ми можемо',('Môžeme sa stretnúť zajtra.','Ми можемо зустрітися завтра.')),
    ('nemôžeme','ми не можемо',('Dnes sa nemôžeme stretnúť.','Сьогодні ми не можемо зустрітися.')),
    ('prepáč','вибач',('Prepáč, meškám.','Вибач, я запізнююся.')),
    ('žiaľ','на жаль',('Žiaľ, nemôžem prísť.','На жаль, я не можу прийти.')),
    ('pôjdeme','ми підемо / поїдемо',('Pôjdeme autobusom.','Ми поїдемо автобусом.')),
    ('stretneme sa','ми зустрінемося',('Stretneme sa o šiestej.','Ми зустрінемося о шостій.')),
    ('potom môžeme','потім ми можемо',('Potom môžeme ísť na kávu.','Потім ми можемо піти на каву.')),
    ('dvere','двері',('To sú dvere.','Це двері.')),
    ('vedľa','поруч',('Banka je vedľa pošty.','Банк поруч із поштою.')),
    ('medzi','між',('Kaviareň je medzi bankou a poštou.','Кав’ярня між банком і поштою.')),
    ('oproti','навпроти',('Lekáreň je oproti banke.','Аптека навпроти банку.')),
    ('nefunguje','не працює',('Výťah nefunguje.','Ліфт не працює.')),
    ('opraviť','полагодити',('Chcem opraviť lampu.','Я хочу полагодити лампу.')),
    ('tečie','тече',('Z kohútika tečie voda.','З крана тече вода.')),
    ('nesvieti','не світить',('Lampa nesvieti.','Лампа не світить.')),
    ('nejde','не працює / не йде',('Výťah nejde.','Ліфт не працює.')),
    ('prísť','прийти',('Technik môže prísť zajtra.','Технік може прийти завтра.')),
    ('prísť pozrieť','прийти подивитися',('Technik môže prísť pozrieť kotol.','Технік може прийти подивитися котел.')),
    ('zavolať','зателефонувати',('Musím zavolať opravára.','Я мушу зателефонувати майстру.')),
    ('sťažovať sa','скаржитися',('Nechcem sa sťažovať na hluk.','Я не хочу скаржитися на шум.')),
    ('rušiť','заважати',('Nechcem rušiť susedov.','Я не хочу заважати сусідам.')),
    ('prenajímať','орендувати',('Chcem prenajímať byt.','Я хочу здавати квартиру в оренду.')),
    ('dostať sa','дістатися',('Ako sa môžem dostať na stanicu?','Як я можу дістатися до вокзалу?')),
    ('odbočiť','повернути',('Tu musíte odbočiť vľavo.','Тут вам потрібно повернути ліворуч.')),
    ('nastúpiť','сісти в транспорт',('Musíte nastúpiť do autobusu.','Вам потрібно сісти в автобус.')),
    ('vystúpiť','вийти з транспорту',('Musíte vystúpiť na tretej zastávke.','Вам потрібно вийти на третій зупинці.')),
    ('prestúpiť','пересісти',('Musíte prestúpiť na električku.','Вам потрібно пересісти на трамвай.')),
    ('vystúpiť','вийти',('Vystúpte na tretej zastávke.','Вийдіть на третій зупинці.')),
    ('trvať','тривати',('Cesta môže trvať desať minút.','Дорога може тривати десять хвилин.')),
    ('smerom','у напрямку',('Choďte smerom k centru.','Ідіть у напрямку центру.')),
    ('odtiaľ','звідти',('Odtiaľ choďte rovno.','Звідти йдіть прямо.')),
    ('tadiaľ','цією дорогою',('Choďte tadiaľ.','Ідіть цією дорогою.')),
    ('pokračovať','продовжувати',('Môžete pokračovať rovno.','Можете продовжувати прямо.')),
    ('mám rád','я люблю',('Mám rád polievku.','Я люблю суп.')),
    ('nemám rád','я не люблю',('Nemám rád mäso.','Я не люблю м’ясо.')),
    ('dosť','достатньо',('Mám dosť vody.','У мене достатньо води.')),
    ('potrebovať','потребувати',('Môžeme potrebovať viac zeleniny.','Нам може знадобитися більше овочів.')),
    ('chýbať','бракувати',('Môže nám chýbať mlieko.','Нам може бракувати молока.')),
    ('kúpiť','купити',('Chcem kúpiť chlieb.','Я хочу купити хліб.')),
    ('sýty','ситий',('Som sýty.','Я ситий.')),
    ('hľadám','я шукаю',('Hľadám oddelenie s elektronikou.','Я шукаю відділ електроніки.')),
    ('máte','у вас є',('Máte túto veľkosť?','У вас є цей розмір?')),
    ('stáť','коштувати',('Koľko to môže stáť?','Скільки це може коштувати?')),
    ('vyskúšať si','приміряти',('Chcem si vyskúšať tieto topánky.','Я хочу приміряти ці черевики.')),
    ('vrátiť','повернути',('Chcem vrátiť tento tovar.','Я хочу повернути цей товар.')),
    ('vymeniť','обміняти',('Chcem vymeniť túto košeľu.','Я хочу обміняти цю сорочку.')),
    ('poslať','надіслати',('Chcem poslať balík.','Я хочу надіслати посилку.')),
    ('vybrať','зняти',('Chcem vybrať hotovosť.','Я хочу зняти готівку.')),
    ('vložiť','внести',('Chcem vložiť peniaze na účet.','Я хочу внести гроші на рахунок.')),
    ('vybaviť','залагодити',('Chcem vybaviť túto vec dnes.','Я хочу владнати цю справу сьогодні.')),
    ('vybavovať','залагоджувати',('Dopoludnia budem vybavovať veci.','До обіду я владнуватиму справи.')),
    ('čakať','чекати',('Musím čakať v rade.','Я мушу чекати в черзі.')),
    ('dokončiť','завершити',('Chcem dokončiť projekt.','Я хочу завершити проєкт.')),
    ('naučiť sa','вивчити / навчитися',('Chcem sa naučiť po slovensky.','Я хочу навчитися говорити словацькою.')),
    ('opakovať','повторювати',('Musím opakovať učivo.','Мені треба повторювати навчальний матеріал.')),
    ('pripraviť sa','підготуватися',('Musím sa pripraviť na skúšku.','Я мушу підготуватися до іспиту.')),
    ('pomôcť','допомогти',('Chcem pomôcť kolegovi.','Я хочу допомогти колезі.')),
    ('rozdeliť si','розподілити між собою',('Musíme si rozdeliť úlohy.','Ми маємо розподілити завдання між собою.')),
    ('pomôcť si','допомогти одне одному',('Môžeme si navzájom pomôcť.','Ми можемо допомогти одне одному.')),
    ('spolupracovať','співпрацювати',('Chcem spolupracovať s tímom.','Я хочу співпрацювати з командою.')),
    ('vyriešiť','вирішити',('Musíme vyriešiť problém.','Ми маємо вирішити проблему.')),
    ('zvládnuť','впоратися',('Chcem zvládnuť túto úlohu.','Я хочу впоратися з цим завданням.')),
    ('hrať','грати',('Chcem hrať futbal.','Я хочу грати у футбол.')),
    ('pozerať','дивитися',('Chcem pozerať film.','Я хочу дивитися фільм.')),
    ('počúvať','слухати',('Chcem počúvať hudbu.','Я хочу слухати музику.')),
    ('páčiť sa','подобатися',('Páči sa mi tento film.','Мені подобається цей фільм.')),
    ('pretože','тому що',('Páči sa mi to, pretože je to zaujímavé.','Мені це подобається, тому що це цікаво.')),
    ('pozvať','запросити',('Chcem pozvať kamarátov.','Я хочу запросити друзів.')),
    ('pridať sa','приєднатися',('Chcem sa pridať k vám.','Я хочу приєднатися до вас.')),
    ('inokedy','іншим разом',('Môžeme sa stretnúť inokedy.','Ми можемо зустрітися іншим разом.')),
    ('nabudúce','наступного разу',('Prídem nabudúce.','Я прийду наступного разу.')),
    ('spolu','разом',('Pôjdeme spolu.','Ми підемо разом.')),
    ('vysvetliť','пояснити',('Môžete mi to vysvetliť?','Можете мені це пояснити?')),
    ('jasné','звісно / добре',('Jasné, pomôžem ti.','Звісно, я тобі допоможу.')),
    ('samozrejme','звичайно',('Samozrejme, pomôžem.','Звичайно, я допоможу.')),
    ('stratiť','загубити',('Nechcem stratiť kľúče.','Я не хочу загубити ключі.')),
    ('poškodiť','пошкодити',('Nechcem poškodiť telefón.','Я не хочу пошкодити телефон.')),
    ('ozvať sa','дати знати / відгукнутися',('Ozvem sa večer.','Я дам знати ввечері.')),
    ('napísať','написати',('Chcem napísať správu.','Я хочу написати повідомлення.')),
    ('odpísať','відповісти',('Musím odpísať na správu.','Я мушу відповісти на повідомлення.')),
    ('potvrdiť','підтвердити',('Chcem potvrdiť termín.','Я хочу підтвердити час.')),
    ('ozvať sa','дати знати',('Ozvem sa večer.','Я дам знати ввечері.')),
    ('dohodnúť','домовитися',('Musíme dohodnúť termín.','Ми маємо домовитися про час.')),
    ('navrhnúť','запропонувати',('Chcem navrhnúť riešenie.','Я хочу запропонувати рішення.')),
    ('súhlasiť','погодитися',('Môžem s tým súhlasiť.','Я можу з цим погодитися.')),
    ('skúsiť','спробувати',('Chcem skúsiť iné riešenie.','Я хочу спробувати інше рішення.')),
    ('meškať','запізнюватися',('Autobus môže meškať desať minút.','Автобус може запізнюватися на десять хвилин.')),
    ('rezervovať','бронювати',('Chcem rezervovať izbu.','Я хочу забронювати номер.')),
    ('zablúdiť','заблукати',('Nechcem zablúdiť v centre.','Я не хочу заблукати в центрі.')),
    ('cítiť sa','почуватися',('Chcem sa cítiť lepšie.','Я хочу почуватися краще.')),
    ('dobre','добре',('Cítim sa dobre.','Я почуваюся добре.')),
    ('zle','погано',('Cítim sa zle.','Я почуваюся погано.')),
    ('kvapky','краплі',('To sú kvapky.','Це краплі.')),
    ('užívať','приймати ліки',('Ako mám užívať tento liek?','Як мені приймати ці ліки?')),
    ('zlepšiť sa','покращитися',('Môj stav sa môže zlepšiť.','Мій стан може покращитися.')),
    ('lebo','бо',('Zostanem doma, lebo som chorý.','Я залишуся вдома, бо я хворий.')),
    ('preto','тому',('Som chorý, preto zostanem doma.','Я хворий, тому залишуся вдома.')),
    ('vybrať si','обрати',('Musím si vybrať jednu možnosť.','Я мушу обрати один варіант.')),
    ('radšej','радше / краще',('Radšej pôjdem vlakom.','Я радше поїду потягом.')),
    ('skôr','скоріше',('Skôr by som išiel vlakom.','Я радше поїхав би потягом.')),
    ('namiesto','замість',('Pôjdem vlakom namiesto autobusu.','Я поїду потягом замість автобуса.')),
    ('určite','точно / безумовно',('Určite prídem.','Я точно прийду.')),
    ('navrhujem','я пропоную',('Navrhujem stretnutie o šiestej.','Я пропоную зустрітися о шостій.')),
    ('vybavené','готово / вирішено',('Je to vybavené.','Це вже владнано.')),
    ('vyhovovať','підходити',('Tento termín mi môže vyhovovať.','Цей час може мені підійти.')),
    ('tešiť sa','радіти / чекати з нетерпінням',('Teším sa na víkend.','Я з нетерпінням чекаю на вихідні.')),
    ('rozhodnúť sa','вирішити / прийняти рішення',('Musím sa rozhodnúť dnes.','Я мушу прийняти рішення сьогодні.')),
]

class ContextualWordExampleTests(unittest.TestCase):
    def test_curated_high_risk_examples(self):
        for sk,uk,expected in CASES:
            with self.subTest(sk=sk,uk=uk):
                self.assertEqual(example_for(sk,uk),expected)

if __name__=='__main__':
    unittest.main()
